config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
normalize:
  outputs:
    prod:
      dbname: db2
      host: localhost
      pass: admin
      port: 5442
      schema: public
      threads: 8
      type: postgres
      user: postgres
  target: prod
